version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly" # We will just check for updates every month.
      day: "monday" # Monday is the default
